version: 2.1
jobs:
  test:
    docker:
      - image: python:3.9.12
    steps:
      - checkout
      - run:
          name: run unit tests
          command: ./run.sh test
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws-cli, kubectl, envsubst
          command: ./install_tools.sh
      - run:
          name: build-push-deploy
          command: ./run.sh deploy
workflows:
  test-build-deploy:
    jobs:
      - test
